# Generated by Django 2.1 on 2019-06-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vl', '0002_auto_20190625_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetable',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
