# Generated by Django 2.1 on 2019-06-27 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vl', '0003_leavetable_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetable',
            name='approval',
        ),
    ]
