# Generated by Django 2.1 on 2019-06-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vl', '0004_remove_leavetable_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetable',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
